# Generated by Django 5.2.15 on 2026-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_plan_slug",
            field=models.CharField(
                blank=True,
                help_text="Plan slug for pending subscription before store creation",
                max_length=100,
                null=True,
                verbose_name="pending subscription plan",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_subscription_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user subscribed (before store creation)",
                null=True,
                verbose_name="pending subscription date",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_trial_start",
            field=models.BooleanField(
                default=False,
                help_text="Whether the pending subscription should start as trial",
                verbose_name="pending trial start",
            ),
        ),
    ]
