# Generated by Django 6.0.6 on 2026-07-01 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_pending_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Organization or workspace name', max_length=200, verbose_name='tenant name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the tenant', max_length=100, unique=True, verbose_name='tenant slug')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active', verbose_name='is active')),
                ('owner', models.ForeignKey(help_text='Primary owner of this tenant', on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='accounts_te_slug_fc353d_idx'), models.Index(fields=['owner', 'is_active'], name='accounts_te_owner_i_15ab86_idx'), models.Index(fields=['created_at', 'is_active'], name='accounts_te_created_068c73_idx')],
            },
        ),
    ]
