# Generated by Django 5.2.15 on 2026-07-19 12:23

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def check_for_duplicate_email_phone(apps, schema_editor):
    """Pre-scan for rows that would violate the partial unique constraints
    we're about to add. Raises a clear, actionable error listing the
    offenders so they can be merged before retrying the migration —
    Postgres would otherwise reject the constraint with a less helpful
    "could not create unique index" message.
    """
    Customer = apps.get_model("messaging", "Customer")
    violations: list[str] = []

    # Duplicate (store, lower(email)) among active customers with non-empty email.
    # Grouping in Python keeps the scan portable across DBs.
    seen: dict[tuple, int] = {}
    for store_id, email in (
        Customer.objects.filter(is_merged=False).exclude(email="").values_list("store_id", "email")
    ):
        key = (store_id, (email or "").lower())
        seen[key] = seen.get(key, 0) + 1
    for (store_id, email), n in seen.items():
        if n > 1:
            violations.append(f"  store={store_id} email={email!r} -> {n} active rows")

    # Duplicate (store, phone) among active customers with non-empty phone
    phone_seen: dict[tuple, int] = {}
    for store_id, phone in (
        Customer.objects.filter(is_merged=False).exclude(phone="").values_list("store_id", "phone")
    ):
        key = (store_id, phone)
        phone_seen[key] = phone_seen.get(key, 0) + 1
    for (store_id, phone), n in phone_seen.items():
        if n > 1:
            violations.append(f"  store={store_id} phone={phone!r} -> {n} active rows")

    if violations:
        raise RuntimeError(
            "\nCannot apply partial unique constraints on messaging_customer:\n"
            + "\n".join(violations)
            + "\n\nResolve these duplicates first (merge the customers via "
            "POST /api/v1/messaging/customers/<id>/merge/ or set is_merged=True "
            "on the duplicates), then re-run the migration."
        )


def noop_reverse(apps, schema_editor):
    """Nothing to undo — the scan is read-only."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_encrypt_plaintext_credentials"),
        ("stores", "0002_store_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerchannelidentity",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this identity's profile is surfaced on the customer card.",
            ),
        ),
        migrations.AddField(
            model_name="customerchannelidentity",
            name="language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 639-1 language code from the channel, if exposed.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customerchannelidentity",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last successful profile refresh from the channel API.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerchannelidentity",
            name="profile_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Last raw profile payload from the channel + per-field source tracking.",
            ),
        ),
        migrations.AddField(
            model_name="customerchannelidentity",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone (e.g. America/New_York) from the channel, if exposed.",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="customerchannelidentity",
            index=models.Index(
                fields=["store", "last_synced_at"], name="messaging_c_store_i_2df6c6_idx"
            ),
        ),
        # Pre-flight: abort before adding constraints if existing data
        # would violate them. Read-only — safe to re-run.
        migrations.RunPython(check_for_duplicate_email_phone, noop_reverse),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                models.F("store"),
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(models.Q(("email", ""), _negated=True), ("is_merged", False)),
                name="uniq_customer_store_email_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                models.F("store"),
                models.F("phone"),
                condition=models.Q(models.Q(("phone", ""), _negated=True), ("is_merged", False)),
                name="uniq_customer_store_phone_active",
            ),
        ),
    ]
