# Generated by Django 5.2.15 on 2026-07-07 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_tenant"),
        ("stores", "0002_store_tenant"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # These tables already have the target names, so we use SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="feature",
                    table="permissions_feature",
                ),
                migrations.AlterModelTable(
                    name="planfeature",
                    table="permissions_planfeature",
                ),
                migrations.AlterModelTable(
                    name="subscription",
                    table="permissions_subscription",
                ),
                migrations.AlterModelTable(
                    name="subscriptionevent",
                    table="permissions_subscriptionevent",
                ),
                migrations.AlterModelTable(
                    name="subscriptionplan",
                    table="permissions_subscriptionplan",
                ),
            ],
            database_operations=[
                # No database changes - tables already have these names
            ],
        ),
    ]

