# Generated by Django 5.2.15 on 2026-07-07 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_tenant"),
        ("stores", "0002_store_tenant"),
        ("subscriptions", "0002_subscription_permissions_status_fbe384_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="subscription",
                    index=models.Index(fields=["status"], name="permissions_status_fbe384_idx"),
                ),
                migrations.AddIndex(
                    model_name="subscription",
                    index=models.Index(
                        fields=["current_period_end"], name="permissions_current_c5d1d1_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="subscriptionevent",
                    index=models.Index(
                        fields=["subscription", "occurred_at"], name="permissions_subscri_ddb1ca_idx"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="planfeature",
                    constraint=models.UniqueConstraint(
                        fields=("plan", "feature"), name="uniq_plan_feature"
                    ),
                ),
            ],
            database_operations=[
                # No database changes - indexes and constraint already exist
            ],
        ),
    ]
