# Generated by Django 5.2.15 on 2026-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_permissions_status_fbe384_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='message_retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Message history retention in days. NULL = unlimited (capped by MESSAGING_MAX_RETENTION_DAYS).', null=True),
        ),
    ]
