# Generated by Django 5.2.15 on 2026-06-11 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="store name"),
                ),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="store slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="store description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="stores/logos/", verbose_name="store logo"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="store settings"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="store managers",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="owned_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="store owners",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="store staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "store",
                "verbose_name_plural": "stores",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="stores_stor_slug_e2ab60_idx"),
                    models.Index(
                        fields=["status", "created_at"], name="stores_stor_status_275131_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("slug",),
                        name="unique_active_store_slug",
                    )
                ],
            },
        ),
    ]
