# Generated by Django 6.0.6 on 2026-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant/workspace this store belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.tenant', verbose_name='tenant'),
        ),
    ]
