# Generated by Django 5.2.15 on 2026-06-24 10:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0002_migrate_legacy_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="after",
            field=models.JSONField(
                blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="before",
            field=models.JSONField(
                blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("approve", "Approve"),
                    ("assign", "Assign"),
                    ("manage", "Manage (all actions)"),
                    ("override_grant", "Override grant"),
                    ("manage_system", "Manage system roles"),
                ],
                max_length=16,
            ),
        ),
    ]
