# Generated by Django 6.0.6 on 2026-07-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant'),
        ('permissions', '0003_alter_auditlog_after_alter_auditlog_before_and_more'),
        ('stores', '0002_store_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store'),
        ),
    ]
