# Generated by Django 5.2.15 on 2026-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_subscription_tenant_alter_subscription_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
