# Generated migration for moving subscription models to subscriptions app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_subscription_stripe_customer_id_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Remove the subscription-related models from permissions app state
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='features',
                ),
                migrations.RemoveField(
                    model_name='planfeature',
                    name='feature',
                ),
                migrations.RemoveField(
                    model_name='planfeature',
                    name='limit_value',
                ),
                migrations.RemoveField(
                    model_name='planfeature',
                    name='plan',
                ),
                migrations.RemoveField(
                    model_name='planfeature',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='planfeature',
                    name='updated_at',
                ),
                migrations.RemoveField(
                    model_name='planfeature',
                    name='id',
                ),
                migrations.DeleteModel(
                    name='PlanFeature',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='billing_period',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='max_users',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='max_stores',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='max_products',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='max_orders_per_month',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='max_warehouses',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='is_active',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='is_public',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='sort_order',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='trial_days',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='updated_at',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='name',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='slug',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='price',
                ),
                migrations.RemoveField(
                    model_name='subscriptionplan',
                    name='id',
                ),
                migrations.DeleteModel(
                    name='SubscriptionPlan',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='store',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='tenant',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='plan',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='status',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='starts_at',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='ends_at',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='trial_ends_at',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='current_period_start',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='current_period_end',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='stripe_customer_id',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='stripe_subscription_id',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='metadata',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='updated_at',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='id',
                ),
                migrations.DeleteModel(
                    name='Subscription',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='subscription',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='event_type',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='occurred_at',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='metadata',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='actor',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='updated_at',
                ),
                migrations.RemoveField(
                    model_name='subscriptionevent',
                    name='id',
                ),
                migrations.DeleteModel(
                    name='SubscriptionEvent',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='code',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='name',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='category',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='updated_at',
                ),
                migrations.RemoveField(
                    model_name='feature',
                    name='id',
                ),
                migrations.DeleteModel(
                    name='Feature',
                ),
            ],
            database_operations=[
                # No database changes - tables remain the same
            ],
        ),
    ]
