# Generated by Django 5.2.15 on 2026-07-09 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0002_store_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="bi-question-circle",
                        help_text="Bootstrap icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(db_index=True, editable=False, max_length=20, unique=True),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=200, validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Issue"),
                            ("billing", "Billing & Subscription"),
                            ("feature", "Feature Request"),
                            ("bug", "Bug Report"),
                            ("account", "Account Management"),
                            ("integration", "Integration Help"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending User Response"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the issue or inquiry",
                        validators=[django.core.validators.MinLengthValidator(50)],
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Screenshot or document attachment",
                        null=True,
                        upload_to="support_attachments/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_response_from",
                    models.CharField(
                        choices=[("user", "User"), ("support", "Support")],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional store related to this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_staff_response",
                    models.BooleanField(
                        default=False, help_text="Whether this comment is from support staff"
                    ),
                ),
                (
                    "content",
                    models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="support_comments/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Internal note - not visible to user"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="help.supportticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("order", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="help.faqcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "question"],
                "indexes": [
                    models.Index(fields=["slug", "is_active"], name="help_faqart_slug_6b15e5_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["ticket_id"], name="help_suppor_ticket__dba677_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "created_at"], name="help_suppor_status_1e209a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["user", "status"], name="help_suppor_user_id_398eb1_idx"),
        ),
    ]
